### ISSUE TITLE
Other Dependency requirements

### ISSUE THREAD

**Issue by Marc-Gee** [SeedSigner/seedsigner-os#1]
Thanks for starting this project !! :) 

When running ./buildfile i
on Ubuntu (2004.2022.1.0), I get a dependency and then a PATH error. can you assist me please? the full console output is attached.  
Error returned is below:

`
&& Configuration written to /home/marc-user/seedsigner-os/build_workdir/.config

Your PATH contains spaces, TABs, and/or newline (\n) characters.
This doesn't work. Fix you PATH.
make[1]: *** [support/dependencies/dependencies.mk:27: dependencies] Error 1
make: *** [Makefile:23: _all] Error 2`

[Console output_1 - Seedsigner-os.txt](https://github.com/DesobedienteTecnologico/seedsigner-os/files/8810179/Console.output_1.-.Seedsigner-os.txt)
Thanks!

**Comment by Marc-Gee** [comment]
I have now found the cause of the error. 
When running your Debian/Ubuntu/Linux OS inside of the _Windows subsystem for Linux aka WSL / WSL2_  , the Linux PATH variable includes the host systems path also, and thats not really compatible with Linux, because the spaces in file names that windows allows are not compatible with Linux commands.

So to correct the error, _before running the ./build i command_ , you should first adjust your Linux path by executing this command, inside your Linux/Debian/Ubuntu WSL instance. 
`$ export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/bin` 

Then the /.build i command executes successfully! 
But the build does take a **long** time to run inside a VM or WSL instance. ie hours.  (thats just the nature of the OS creation)
:)

**Comment by DesobedienteTecnologico** [comment]
> I have now found the cause of the error. When running your Debian/Ubuntu/Linux OS inside of the _Windows subsystem for Linux aka WSL / WSL2_ , the Linux PATH variable includes the host systems path also, and thats not really compatible with Linux, because the spaces in file names that windows allows are not compatible with Linux commands.
> 
> So to correct the error, _before running the ./build i command_ , you should first adjust your Linux path by executing this command, inside your Linux/Debian/Ubuntu WSL instance. `$ export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/bin`
> 
> Then the /.build i command executes successfully! But the build does take a **long** time to run inside a VM or WSL instance. ie hours. (thats just the nature of the OS creation) :)

Thanks for sharing with us @Marc-Gee !
:)

Regards
