### ISSUE TITLE
Feature Request: Temporarily cache multi-sig wallet configuration on device and allow users to select it during transaction signing.

### ISSUE THREAD

**Issue by austinvach** [SeedSigner/seedsigner-os#42]
I've been playing around with multi-sig vaults on Blue Wallet and I'm using SeedSigner to manage all the keys. Everything works well until I try to send from the multi-sig wallet. 

**The Context:** Once you enter a receiving address and amount to be sent, Blue Wallet displays a screen asking for the required number of signatures. After clicking "Provide signature" under a specific key ([see here for a visual](https://youtu.be/V7hzuerITOM?t=41)), Blue Wallet generates a QR code that needs to be scanned by the SeedSigner. Once scanned, SeedSigner shows the transaction info but can't confirm the change address until you scan the multi-sig configuration information.

**The Problem:** In order to get back to the multi-sig configuration information in Blue Wallet, you need to back out of the current transaction which means it's not possible to confirm the change address without scanning that info from a QR code that you've saved outside of Blue Wallet.

**The Feature Request:**
Allow users to scan multi-sig configuration information into the SeedSigner and temporarily cache that information so that it can be referenced during transaction signing.

Does that make sense?

Thank you all for your work on this project. It's awesome.

**Comment by DesobedienteTecnologico** [comment]
Hi, thanks for your interest on this.

I believe that this issue should be created on [SeedSigner](https://github.com/SeedSigner/seedsigner) repository instead [SeedSignerOS](https://github.com/SeedSigner/seedsigner-os).
In this repository we have mainly the OS, and in [SeedSigner](https://github.com/SeedSigner/seedsigner) the software that creates files and interact with them and also all regarding UI/UX.

Could you please create this issue in [SeedSigner](https://github.com/SeedSigner/seedsigner) repository?

Regards
