### ISSUE TITLE
Feature request: unlock keyboard (word suggestions) to use seed in other languages

### ISSUE THREAD

**Issue by Tsunaide** [SeedSigner/seedsigner-os#46]
Hi,

I am using a multisig scheme with 3 seeds in different languages. It works on electrum wallet. For example: one seed in portuguese, another seed in italian and other seed in czech.... But in my SeedSigner just seeds in english are available...

Thank you!

**Comment by bitcoinprecept** [comment]
I'm not sure what it means to have a seed in other languages exactly. English is the only officially supported language of BIP39, no? Are there broadly accepted word lists that correspond 1:1 with the English list?

**Comment by Tsunaide** [comment]
All languages bip39

https://github.com/bitcoin/bips/tree/master/bip-0039

**Comment by Tsunaide** [comment]
Other source to see all mmemonic languages:
https://iancoleman.io/bip39/

**Comment by bitcoinprecept** [comment]
Thanks for those links.

Your feature request is probably better suited for the actual seedsigner repo. This repo is only the OS underlying the seed interaction software.
