### ISSUE TITLE
How to troubleshoot blank screen?

### ISSUE THREAD

**Issue by iberjoinbrella** [SeedSigner/seedsigner-os#49]
I get a blank screen on the display and splash screen on HDMI forever, no cpu light after it blinks a few times on boot.
How can I troubleshoot this? are there any logs persisted on the sd card that I can read?

**Comment by jdlcdl** [comment]
The standard rpi rainbow splash on hdmi is normal while the RPi is looking to boot.  As well, the waveshare hat's backlight will illuminate as soon as it's powered on but it will remain black until your seedsigner has booted (30-50 seconds depending on which model you have).

If nothing happens after that, then you should suspect problems on your microsd card.  Make sure that it's version 0.6.0, you can download the image for all supported boards [here](https://github.com/SeedSigner/seedsigner/releases/tag/0.6.0) and follow the instructions for verifying and installing [here](https://github.com/SeedSigner/seedsigner#verifying-that-the-downloaded-files-are-authentic-optional-but-highly-recommended).

**Comment by DesobedienteTecnologico** [comment]
-dev release allows you to use the HDMI, but is only recommended for developers.

Thanks for the exaplanations @jdlcdl
