### ISSUE TITLE
Double button click instead of joystick click

### ISSUE THREAD

**Issue by plebcoach** [SeedSigner/seedsigner-os#68]
Is there a way to use two buttons (of the 3-button row to the right) simultaniously instead of the joystick middle click? My joystick is broken and this would allow me to keep the device. Just getting into programming so I don´t know how feasible that is....

**Comment by newtonick** [comment]
This is not likely something that would be implemented. You can look here if you want to hack something together, but it would be not be straight forward to accomplish. https://github.com/SeedSigner/seedsigner/blob/dev/src/seedsigner/hardware/buttons.py
